2021-10-09 20:49:31,037 INFO    MainThread:18372 [wandb_setup.py:_flush():69] setting env: {}
2021-10-09 20:49:31,038 INFO    MainThread:18372 [wandb_setup.py:_flush():69] setting login settings: {}
2021-10-09 20:49:31,039 INFO    MainThread:18372 [wandb_init.py:_log_setup():357] Logging user logs to C:\report\OgeettiiBot\server\wandb\run-20211009_204931-1oxmsz3w\logs\debug.log
2021-10-09 20:49:31,040 INFO    MainThread:18372 [wandb_init.py:_log_setup():358] Logging internal logs to C:\report\OgeettiiBot\server\wandb\run-20211009_204931-1oxmsz3w\logs\debug-internal.log
2021-10-09 20:49:31,041 INFO    MainThread:18372 [wandb_init.py:init():390] calling init triggers
2021-10-09 20:49:31,042 INFO    MainThread:18372 [wandb_init.py:init():395] wandb.init called with sweep_config: {}
config: {}
2021-10-09 20:49:31,043 INFO    MainThread:18372 [wandb_init.py:init():435] starting backend
2021-10-09 20:49:31,044 INFO    MainThread:18372 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn, using: spawn
2021-10-09 20:49:31,057 INFO    MainThread:18372 [backend.py:ensure_launched():135] starting backend process...
2021-10-09 20:49:31,875 INFO    MainThread:18372 [backend.py:ensure_launched():139] started backend process with pid: 11792
2021-10-09 20:49:31,876 INFO    MainThread:18372 [wandb_init.py:init():440] backend started and connected
2021-10-09 20:49:31,994 INFO    MainThread:18372 [wandb_init.py:init():499] updated telemetry
2021-10-09 20:49:31,995 INFO    MainThread:18372 [wandb_init.py:init():522] communicating current version
2021-10-09 20:49:35,419 INFO    MainThread:18372 [wandb_init.py:init():527] got version response 
2021-10-09 20:49:35,420 INFO    MainThread:18372 [wandb_init.py:init():535] communicating run to backend with 30 second timeout
2021-10-09 20:50:05,426 INFO    MainThread:18372 [interface.py:_communicate_run():651] couldn't get run from backend
2021-10-09 20:50:05,426 ERROR   MainThread:18372 [wandb_init.py:init():540] backend process timed out
2021-10-09 20:50:05,427 ERROR   MainThread:18372 [wandb_init.py:init():549] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2021-10-09 20:51:00,555 INFO    MainThread:18372 [wandb_init.py:teardown():205] tearing down wandb.init
